In [4]:

import tkinter as tk
from tkinter import messagebox
import numpy as np

data = None

def set_data():
    global data
    start = float(entry1.get())
    to = float(entry2.get())
    step = float(entry3.get())
    data = np.arange(start, to, step)
    print(data)
    return data

rt = tk.Tk()
rt.title("numpy playground")

entry1 = tk.Entry(rt)
entry1.grid(row = 0, column = 0)

label1 = tk.Label(rt, text = "from")
label1.grid(row = 0, column = 1)

entry2 = tk.Entry(rt)
entry2.grid(row = 0, column = 2)

label2 = tk.Label(rt, text = "to")
label2.grid(row = 0, column = 3)

entry3 = tk.Entry(rt)
entry3.grid(row = 0, column = 4)

label3 = tk.Label(rt, text = "step")
label3.grid(row = 0, column = 5)

button1 = tk.Button(text = "save?", command = set_data)
button1.grid(row = 0, column = 6)

entry4 = tk.Entry(rt)
entry4.grid(row = 1, column = 0)

entry5 = tk.Entry(rt)
entry5.grid(row = 1, column = 1)

def change_dimension():
    try:
        global data
        data.shape = (int(entry4.get()), int(entry5.get()))
        print(data)
    except Exception as e:
        messagebox.showerror("오류", f"차원을 올바르게 입력하시오: {e}")

button2 = tk.Button(rt, text = "change dimension", command = change_dimension)
button2.grid(row = 1, column = 2)

entry6 = tk.Entry(rt)
entry6.grid(row = 2, column = 0)

def plus_elements():
    try:
        global data
        value = float(entry6.get())
        data = data + value
        label4.config(text = str(data))
        print(data)
    except Exception as e:
        messagebox.showerror("오류", f"{e}")

button3 = tk.Button(rt, text = "+", command = plus_elements)
button3.grid(row = 2, column = 1)


entry7 = tk.Entry(rt)
entry7.grid(row = 3, column = 0)

def mul_elements():
    try:
        global data
        data = data * float(entry7.get())
        label4.config(text = str(data))
        print(data)
    except Exception as e:
        messagebox.showerror("오류", f"{e}")

button4 = tk.Button(rt, text = "*", command= mul_elements).grid(row = 3, column = 1)

label4 = tk.Label(rt, text = "")
label4.grid(row = 4, column = 0)


rt.mainloop()

[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[ 3.  6.  9.]
 [12. 15. 18.]
 [21. 24. 27.]]
[[ 9. 18. 27.]
 [36. 45. 54.]
 [63. 72. 81.]]
[[ 27.  54.  81.]
 [108. 135. 162.]
 [189. 216. 243.]]
[[ 81. 162. 243.]
 [324. 405. 486.]
 [567. 648. 729.]]
[[ 243.  486.  729.]
 [ 972. 1215. 1458.]
 [1701. 1944. 2187.]]
[[ 729. 1458. 2187.]
 [2916. 3645. 4374.]
 [5103. 5832. 6561.]]
[[ 2187.  4374.  6561.]
 [ 8748. 10935. 13122.]
 [15309. 17496. 19683.]]
[[ 6561. 13122. 19683.]
 [26244. 32805. 39366.]
 [45927. 52488. 59049.]]
[[ 19683.  39366.  59049.]
 [ 78732.  98415. 118098.]
 [137781. 157464. 177147.]]
[[ 59049. 118098. 177147.]
 [236196. 295245. 354294.]
 [413343. 472392. 531441.]]
[[ 177147.  354294.  531441.]
 [ 708588.  885735. 1062882.]
 [1240029. 1417176. 1594323.]]
[[ 531441. 1062882. 1594323.]
 [2125764. 2657205. 3188646.]
 [3720087. 4251528. 4782969.]]
[[ 1594323.  3188646.  4782969.]
 [ 6377292.  7971615.  9565938.]
 [11160261. 12754584. 14348907.]]
[[ 4782969. 

In [ ]:
import tkinter as tk
from tkinter import messagebox
import numpy as np

root = tk.Tk()
root.title("행렬곱 계산")

data = None
data2 = None
data_result = None

label1 = tk.Label(root, text="first matrix", fg="red").grid(row=0, column=0)

entry11 = tk.Entry(root)
entry11.grid(row=1, column=1)

label11 = tk.Label(root, text="from")
label11.grid(row=1, column=2)

entry22 = tk.Entry(root)
entry22.grid(row=1, column=3)

label22 = tk.Label(root, text="to")
label22.grid(row=1, column=4)

entry33 = tk.Entry(root)
entry33.grid(row=1, column=5)

label33 = tk.Label(root, text="step")
label33.grid(row=1, column=6)

def save_first_matrix():
    try:
        global data 
        data = np.arange(float(entry11.get()), float(entry22.get()), float(entry33.get()))
        print(data)
        return data
    except Exception as e:
        messagebox.showerror("error", f"{e}")

button2 = tk.Button(root, text="save", fg="red", command=save_first_matrix).grid(row=1, column=7)

label2 = tk.Label(root, text="decide dimension").grid(row=2, column=1)
entry1 = tk.Entry(root)
entry1.grid(row=2, column=2)
label3 = tk.Label(root, text="x").grid(row=2, column=3)
entry2 = tk.Entry(root)
entry2.grid(row=2, column=4)

def reshape_first_matrix():
    global data
    try:
        data.shape = (int(entry1.get()), int(entry2.get()))
        print(data)
        return data
    except Exception as e:
        messagebox.showerror("error", f"{e}")

button1 = tk.Button(root, text="save", fg="red", command=reshape_first_matrix).grid(row=2, column=5)

label4 = tk.Label(root, text="second matrix", fg="blue").grid(row=3, column=0)

entry44 = tk.Entry(root)
entry44.grid(row=4, column=1)

label44 = tk.Label(root, text="from")
label44.grid(row=4, column=2)

entry55 = tk.Entry(root)
entry55.grid(row=4, column=3)

label55 = tk.Label(root, text="to")
label55.grid(row=4, column=4)

entry66 = tk.Entry(root)
entry66.grid(row=4, column=5)

label66 = tk.Label(root, text="step")
label66.grid(row=4, column=6)

def save_second_matrix():
    try:
        global data2 
        data2 = np.arange(float(entry44.get()), float(entry55.get()), float(entry66.get()))
        print(data2)
        return data2
    except Exception as e:
        messagebox.showerror("error", f"{e}")

button3 = tk.Button(root, text="save", fg="blue", command=save_second_matrix).grid(row=4, column=7)

label5 = tk.Label(root, text="decide dimension").grid(row=5, column=1)
entry3 = tk.Entry(root)
entry3.grid(row=5, column=2)
label6 = tk.Label(root, text="x").grid(row=5, column=3)
entry4 = tk.Entry(root)
entry4.grid(row=5, column=4)

def reshape_second_matrix():
    global data2
    try:
        data2.shape = (int(entry3.get()), int(entry4.get()))
        print(data2)
        return data2
    except Exception as e:
        messagebox.showerror("error", f"{e}")

button4 = tk.Button(root, text="save", fg="blue", command=reshape_second_matrix).grid(row=5, column=5)

label7 = tk.Label(root, text = ". . .", width=10, height=10)
label7.grid(row = 7, column = 0)

def letsfuckinggo():
    global data_result, data, data2
    try:
        data_result = np.dot(data, data2)
        label7.config(text= str(data_result))
        print(data_result)
        return data_result
    except Exception as e:
        messagebox.showerror("error", f"{e}")

button5 = tk.Button(root, text = "Calculate !!",fg = "green",  command = letsfuckinggo).grid(row = 6, column = 0)

root.mainloop()


[1. 4. 7.]
[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[ 3.  4.  5.  6.  7.  8.  9. 10. 11.]
[[ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]
[[ 42.  48.  54.]
 [ 96. 111. 126.]
 [150. 174. 198.]]
