In [29]:
import tkinter as tk
from tkinter import messagebox
import numpy as np

data = None

def set_data():
    global data
    start = float(entry1.get())
    to = float(entry2.get())
    step = float(entry3.get())
    data = np.arange(start, to, step)
    print(data)
    return data

rt = tk.Tk()
rt.geometry("900x600")
rt.title("numpy playground")

entry1 = tk.Entry(rt)
entry1.grid(row = 0, column = 0)

label1 = tk.Label(rt, text = "from")
label1.grid(row = 0, column = 1)

entry2 = tk.Entry(rt)
entry2.grid(row = 0, column = 2)

label2 = tk.Label(rt, text = "to")
label2.grid(row = 0, column = 3)

entry3 = tk.Entry(rt)
entry3.grid(row = 0, column = 4)

label3 = tk.Label(rt, text = "step")
label3.grid(row = 0, column = 5)

button1 = tk.Button(text = "save?", command = set_data)
button1.grid(row = 0, column = 6)

entry4 = tk.Entry(rt)
entry4.grid(row = 1, column = 0)

entry5 = tk.Entry(rt)
entry5.grid(row = 1, column = 1)

def change_dimension():
    try:
        global data
        data.shape = (int(entry4.get()), int(entry5.get()))
        print(data)
    except Exception as e:
        messagebox.showerror("오류", f"차원을 올바르게 입력하시오: {e}")

button2 = tk.Button(rt, text = "change dimension", command = change_dimension)
button2.grid(row = 1, column = 2)

entry6 = tk.Entry(rt)
entry6.grid(row = 2, column = 0)

def plus_elements():
    try:
        global data
        value = float(entry6.get())
        data = data + value
        print(data)
    except Exception as e:
        messagebox.showerror("오류", f"{e}")

button3 = tk.Button(rt, text = "+", command = plus_elements)
button3.grid(row = 2, column = 1)

rt.mainloop()

[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]
