In [ ]:
# ver 1.0
import tkinter as tk
from tkinter import messagebox
import numpy as np

data = None

def set_data():
    global data
    start = float(entry1.get())
    to = float(entry2.get())
    step = float(entry3.get())
    data = np.arange(start, to, step)
    print(data)
    return data

rt = tk.Tk()
rt.title("numpy playground")

entry1 = tk.Entry(rt)
entry1.grid(row = 0, column = 0)

label1 = tk.Label(rt, text = "from")
label1.grid(row = 0, column = 1)

entry2 = tk.Entry(rt)
entry2.grid(row = 0, column = 2)

label2 = tk.Label(rt, text = "to")
label2.grid(row = 0, column = 3)

entry3 = tk.Entry(rt)
entry3.grid(row = 0, column = 4)

label3 = tk.Label(rt, text = "step")
label3.grid(row = 0, column = 5)

button1 = tk.Button(text = "save?", command = set_data)
button1.grid(row = 0, column = 6)

entry4 = tk.Entry(rt)
entry4.grid(row = 1, column = 0)

entry5 = tk.Entry(rt)
entry5.grid(row = 1, column = 1)

def change_dimension():
    try:
        global data
        data.shape = (int(entry4.get()), int(entry5.get()))
        print(data)
    except Exception as e:
        messagebox.showerror("오류", f"차원을 올바르게 입력하시오: {e}")

button2 = tk.Button(rt, text = "change dimension", command = change_dimension)
button2.grid(row = 1, column = 2)

entry6 = tk.Entry(rt)
entry6.grid(row = 2, column = 0)

def plus_elements():
    try:
        global data
        value = float(entry6.get())
        data = data + value
        label4.config(text = str(data))
        print(data)
    except Exception as e:
        messagebox.showerror("오류", f"{e}")

button3 = tk.Button(rt, text = "+", command = plus_elements)
button3.grid(row = 2, column = 1)


entry7 = tk.Entry(rt)
entry7.grid(row = 3, column = 0)

def mul_elements():
    try:
        global data
        data = data * float(entry7.get())
        label4.config(text = str(data))
        print(data)
    except Exception as e:
        messagebox.showerror("오류", f"{e}")

button4 = tk.Button(rt, text = "*", command= mul_elements).grid(row = 3, column = 1)

label4 = tk.Label(rt, text = "")
label4.grid(row = 4, column = 0)

rt.mainloop()

In [43]:
# ver 2.0
import tkinter as tk
from tkinter import messagebox
import numpy as np

root = tk.Tk()
root.title("행렬곱 계산")

data = None
data2 = None
data_result = None

label1 = tk.Label(root, text="first matrix", fg="red").grid(row=0, column=0)

entry11 = tk.Entry(root)
entry11.grid(row=1, column=1)

label11 = tk.Label(root, text="from")
label11.grid(row=1, column=2)

entry22 = tk.Entry(root)
entry22.grid(row=1, column=3)

label22 = tk.Label(root, text="to")
label22.grid(row=1, column=4)

entry33 = tk.Entry(root)
entry33.grid(row=1, column=5)

label33 = tk.Label(root, text="step")
label33.grid(row=1, column=6)

def save_first_matrix():
    try:
        global data 
        data = np.arange(float(entry11.get()), float(entry22.get()), float(entry33.get()))
        print(data)
        return data
    except Exception as e:
        messagebox.showerror("error", f"{e}")

button2 = tk.Button(root, text="save", fg="red", command=save_first_matrix).grid(row=1, column=7)

label2 = tk.Label(root, text="decide dimension").grid(row=2, column=1)
entry1 = tk.Entry(root)
entry1.grid(row=2, column=2)
label3 = tk.Label(root, text="x").grid(row=2, column=3)
entry2 = tk.Entry(root)
entry2.grid(row=2, column=4)

def reshape_first_matrix():
    global data
    try:
        data.shape = (int(entry1.get()), int(entry2.get()))
        print(data)
        return data
    except Exception as e:
        messagebox.showerror("error", f"{e}")

button1 = tk.Button(root, text="save", fg="red", command=reshape_first_matrix).grid(row=2, column=5)

label4 = tk.Label(root, text="second matrix", fg="blue").grid(row=3, column=0)

entry44 = tk.Entry(root)
entry44.grid(row=4, column=1)

label44 = tk.Label(root, text="from")
label44.grid(row=4, column=2)

entry55 = tk.Entry(root)
entry55.grid(row=4, column=3)

label55 = tk.Label(root, text="to")
label55.grid(row=4, column=4)

entry66 = tk.Entry(root)
entry66.grid(row=4, column=5)

label66 = tk.Label(root, text="step")
label66.grid(row=4, column=6)

def save_second_matrix():
    try:
        global data2 
        data2 = np.arange(float(entry44.get()), float(entry55.get()), float(entry66.get()))
        print(data2)
        return data2
    except Exception as e:
        messagebox.showerror("error", f"{e}")

button3 = tk.Button(root, text="save", fg="blue", command=save_second_matrix).grid(row=4, column=7)

label5 = tk.Label(root, text="decide dimension").grid(row=5, column=1)
entry3 = tk.Entry(root)
entry3.grid(row=5, column=2)
label6 = tk.Label(root, text="x").grid(row=5, column=3)
entry4 = tk.Entry(root)
entry4.grid(row=5, column=4)

def reshape_second_matrix():
    global data2
    try:
        data2.shape = (int(entry3.get()), int(entry4.get()))
        print(data2)
        return data2
    except Exception as e:
        messagebox.showerror("error", f"{e}")

button4 = tk.Button(root, text="save", fg="blue", command=reshape_second_matrix).grid(row=5, column=5)

label7 = tk.Label(root, text = ". . .", width=10, height=10)
label7.grid(row = 7, column = 0)


def letsfuckinggo():
    global data_result, data, data2
    try:
        data_result = np.dot(data, data2)
        label7.config(text= str(data_result))
        print(data_result)
        return data_result
    except Exception as e:
        messagebox.showerror("error", f"{e}")

button5 = tk.Button(root, text = "Calculate !!",fg = "green",  command = letsfuckinggo).grid(row = 6, column = 0)


root.mainloop()


In [ ]:
# ver 2.1
import tkinter as tk
from tkinter import messagebox
import numpy as np

root = tk.Tk()
root.title("행렬곱 계산")

data = None
data2 = None
data_result = None

label1 = tk.Label(root, text="first matrix", fg="red").grid(row=0, column=0)

entry11 = tk.Entry(root)
entry11.grid(row=1, column=1)

label11 = tk.Label(root, text="from")
label11.grid(row=1, column=2)

entry22 = tk.Entry(root)
entry22.grid(row=1, column=3)

label22 = tk.Label(root, text="to")
label22.grid(row=1, column=4)

entry33 = tk.Entry(root)
entry33.grid(row=1, column=5)

label33 = tk.Label(root, text="step")
label33.grid(row=1, column=6)

def save_first_matrix():
    try:
        global data 
        data = np.arange(float(entry11.get()), float(entry22.get()), float(entry33.get()))
        print(data)
        label_middle.config(text = str(data))
        return data
    except Exception as e:
        messagebox.showerror("error", f"{e}")

button2 = tk.Button(root, text="save", fg="red", command=save_first_matrix).grid(row=1, column=7)

label2 = tk.Label(root, text="decide dimension").grid(row=2, column=1)
entry1 = tk.Entry(root)
entry1.grid(row=2, column=2)
label3 = tk.Label(root, text="x").grid(row=2, column=3)
entry2 = tk.Entry(root)
entry2.grid(row=2, column=4)

def reshape_first_matrix():
    global data
    try:
        data.shape = (int(entry1.get()), int(entry2.get()))
        print(data)
        label_middle.config(text= str(data))
        return data
    except Exception as e:
        messagebox.showerror("error", f"{e}")

button1 = tk.Button(root, text="save", fg="red", command=reshape_first_matrix).grid(row=2, column=5)

label_middle = tk.Label(root, text=". . .", fg="black")
label_middle.grid(row=3, column=0)

label4 = tk.Label(root, text="second matrix", fg="blue").grid(row=5, column=0)

entry44 = tk.Entry(root)
entry44.grid(row=6, column=1)

label44 = tk.Label(root, text="from")
label44.grid(row=6, column=2)

entry55 = tk.Entry(root)
entry55.grid(row=6, column=3)

label55 = tk.Label(root, text="to")
label55.grid(row=6, column=4)

entry66 = tk.Entry(root)
entry66.grid(row=6, column=5)

label66 = tk.Label(root, text="step")
label66.grid(row=6, column=6)

def save_second_matrix():
    try:
        global data2 
        data2 = np.arange(float(entry44.get()), float(entry55.get()), float(entry66.get()))
        print(data2)
        label8.config(text = str(data2))
        return data2
    except Exception as e:
        messagebox.showerror("error", f"{e}")

button3 = tk.Button(root, text="save", fg="blue", command=save_second_matrix).grid(row=6, column=7)

label5 = tk.Label(root, text="decide dimension").grid(row=7, column=1)
entry3 = tk.Entry(root)
entry3.grid(row=7, column=2)
label6 = tk.Label(root, text="x").grid(row=7, column=3)
entry4 = tk.Entry(root)
entry4.grid(row=7, column=4)

def reshape_second_matrix():
    global data2
    try:
        data2.shape = (int(entry3.get()), int(entry4.get()))
        print(data2)
        label8.config(text = str(data2))
        return data2
    except Exception as e:
        messagebox.showerror("error", f"{e}")

button4 = tk.Button(root, text="save", fg="blue", command=reshape_second_matrix).grid(row=7, column=5)

label8 = tk.Label(root, text = ". . .")
label8.grid(row = 8, column = 0)

label7 = tk.Label(root, text=". . .", width=10, height=10)
label7.grid(row=10, column=0)

def letsfuckinggo():
    global data_result, data, data2
    try:
        data_result = np.dot(data, data2)
        label7.config(text=str(data_result))
        print(data_result)
        return data_result
    except Exception as e:
        messagebox.showerror("error", f"{e}")

button5 = tk.Button(root, text="Calculate !!", fg="green", command=letsfuckinggo).grid(row=9, column=0)

button6 = tk.Button()

root.mainloop()

[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[10. 11. 12. 13. 14. 15. 16. 17. 18.]
[[10. 11. 12.]
 [13. 14. 15.]
 [16. 17. 18.]]
[[ 84.  90.  96.]
 [201. 216. 231.]
 [318. 342. 366.]]


In [18]:
# ver 3.2
import tkinter as tk
from tkinter import messagebox
import numpy as np
import random

root = tk.Tk()
root.title("넘파이 계산기")
root.geometry("1000x600")

data = None
data2 = None
data_result = None

frame1 = tk.LabelFrame(root, text="첫 번째 행렬", fg="red", padx=10, pady=10)
frame1.grid(row=0, column=0, padx=10, pady=10, sticky="nsew")

tk.Label(frame1, text="From").grid(row=0, column=0)
entry11 = tk.Entry(frame1)
entry11.grid(row=0, column=1)

tk.Label(frame1, text="To").grid(row=0, column=2)
entry22 = tk.Entry(frame1)
entry22.grid(row=0, column=3)

tk.Label(frame1, text="Step").grid(row=0, column=4)
entry33 = tk.Entry(frame1)
entry33.grid(row=0, column=5)



def save_first_matrix():
    try:
        global data
        data = np.arange(float(entry11.get()), float(entry22.get()), float(entry33.get()))
        print(data)
        label_first_matrix.config(text=str(data))
    except Exception as e:
        messagebox.showerror("Error", f"{e}")

tk.Button(frame1, text="Save", fg="red", command=save_first_matrix).grid(row=0, column=6)

tk.Label(frame1, text="차원 변경").grid(row=1, column=0, columnspan=2)
entry1 = tk.Entry(frame1)
entry1.grid(row=1, column=2)
tk.Label(frame1, text="x").grid(row=1, column=3)
entry2 = tk.Entry(frame1)
entry2.grid(row=1, column=4)

def print_dimention():
    try :
        global data
        check_dimention_label1.config(text = f"{str(data.ndim)}차원 입니다.")
    except Exception as e:
        messagebox.showerror("Error", f"올바른 행렬을 입력해라ㅋ \n{e}")


tk.Button(frame1, text = "차원 확인", command = print_dimention).grid(row = 2, column = 0)
check_dimention_label1 = tk.Label(frame1, text = "...")
check_dimention_label1.grid(row = 2, column = 1)

def reshape_first_matrix():
    global data
    try:
        data.shape = (int(entry1.get()), int(entry2.get()))
        print(data)
        label_first_matrix.config(text=str(data))
    except Exception as e:
        messagebox.showerror("Error", f"{e}")

tk.Button(frame1, text="Reshape", fg="red", command=reshape_first_matrix).grid(row=1, column=5)

label_first_matrix = tk.Label(frame1, text=". . .", fg="black")
label_first_matrix.grid(row=0, column=7, rowspan=2)

frame2 = tk.LabelFrame(root, text="두 번째 행렬", fg="blue", padx=10, pady=10)
frame2.grid(row=1, column=0, padx=10, pady=10, sticky="nsew")

tk.Label(frame2, text="From").grid(row=0, column=0)
entry44 = tk.Entry(frame2)
entry44.grid(row=0, column=1)

tk.Label(frame2, text="To").grid(row=0, column=2)
entry55 = tk.Entry(frame2)
entry55.grid(row=0, column=3)

tk.Label(frame2, text="Step").grid(row=0, column=4)
entry66 = tk.Entry(frame2)
entry66.grid(row=0, column=5)

def save_second_matrix():
    try:
        global data2
        data2 = np.arange(float(entry44.get()), float(entry55.get()), float(entry66.get()))
        print(data2)
        label_second_matrix.config(text=str(data2))
    except Exception as e:
        messagebox.showerror("Error", f"{e}")

tk.Button(frame2, text="Save", fg="blue", command=save_second_matrix).grid(row=0, column=6)

tk.Label(frame2, text="차원").grid(row=1, column=0, columnspan=2)
entry3 = tk.Entry(frame2)
entry3.grid(row=1, column=2)
tk.Label(frame2, text="x").grid(row=1, column=3)
entry4 = tk.Entry(frame2)
entry4.grid(row=1, column=4)

def show_demention_label0():
    try:
        global data
        show_demention_label2.config(text = f"{str(data.ndim)}차원 입니다")
    except Exception as e:
        messagebox.showerror("Error", f"올바른 행렬을 입력해라\n {e}")
    

print_dimention_button = tk.Button(frame2, text = "차원을 보여주세옹", command = show_demention_label0).grid(row = 2, column = 0)
show_demention_label2 = tk.Label(frame2, text = "...")
show_demention_label2.grid(row = 2, column = 1)

def reshape_second_matrix():
    global data2
    try:
        data2.shape = (int(entry3.get()), int(entry4.get()))
        print(data2)
        label_second_matrix.config(text=str(data2))
    except Exception as e:
        messagebox.showerror("Error", f"{e}")

tk.Button(frame2, text="Reshape", fg="blue", command=reshape_second_matrix).grid(row=1, column=5)

label_second_matrix = tk.Label(frame2, text=". . .", fg="black")
label_second_matrix.grid(row=0, column=7, rowspan=2)

#---------------------------------------------------------------------------------------------------------------------------

frame3 = tk.LabelFrame(root, text="요소 연산", padx=10, pady=10)
frame3.grid(row=2, column=0, padx=10, pady=10, sticky="nsew")

tk.Label(frame3, text="첫 번째 행렬").grid(row=0, column=0, columnspan=2)
entry_1 = tk.Entry(frame3)
entry_1.grid(row=0, column=2)

def add_elements_first():
    try:
        global data
        value = float(entry_1.get())
        data = data + value
        print(data)
        label_first_matrix.config(text=str(data))
    except Exception as e:
        messagebox.showerror("Error", f"{e}")

tk.Button(frame3, text="Add", command=add_elements_first).grid(row=0, column=3)

def subtract_element():
    try:
        global data
        value = float(entry_1.get())
        data -= value
        label_first_matrix.config(text = str(data))
    except Exception as e:
        messagebox.showerror("Error", f"{e}")

tk.Button(frame3, text = "Subtract", command = subtract_element).grid(row = 0, column = 4)

def multiply_element():
    try:
        global data
        value = int(entry_1.get())
        data *= value
        label_first_matrix.config(text = str(data))
    except Exception as e:
        messagebox.showerror("Error", f"{e}")

tk.Button(frame3, text = "multiply", command = multiply_element).grid(row = 0, column = 5)

def transgender():
    try:
        global data 
        data = np.transpose(data)
        label_first_matrix.config(text = str(data))
    except Exception as e:
        messagebox.showerror("Error", f"{e}")

tk.Button(frame3, text = "transpose", command = transgender).grid(row = 0, column = 6)

tk.Label(frame3, text="두 번째 행렬").grid(row=1, column=0, columnspan=2)
entry_2 = tk.Entry(frame3)
entry_2.grid(row=1, column=2)

def add_elements_second():
    try:
        global data2
        value = float(entry_2.get())
        data2 = data2 + value
        print(data2)
        label_second_matrix.config(text=str(data2))
    except Exception as e:
        messagebox.showerror("Error", f"{e}")

tk.Button(frame3, text="Add", command=add_elements_second).grid(row=1, column=3)

def subtract_element2():
    try:
        global data2
        value = float(entry_2.get())
        data2 -= value
        label_second_matrix.config(text = str(data2))
    except Exception as e:
        messagebox.showerror("Error", f"{e}")

tk.Button(frame3, text = "Subtract", command = subtract_element2).grid(row = 1, column = 4)

def multiply_element2():
    try:
        global data2 
        value = int(entry_2.get())
        data2 *= value
        label_second_matrix.config(text = str(data2))
    except Exception as e:
        messagebox.showerror("Error", f"{e}")

tk.Button(frame3, text = "multiply", command = multiply_element2).grid(row = 1, column = 5)

def tetetetetetellme():
    try:
        global data2
        data2 = np.transpose(data2)
        label_second_matrix.config(text = str(data2))
    except Exception as e:
        messagebox.showerror("Error", f"{e}")



tk.Button(frame3, text = "transpose", command = tetetetetetellme).grid(row = 1, column = 6)

#------------------------------------------------------------------------------------------------------------------------

frame4 = tk.LabelFrame(root, text="행렬 연산", padx=10, pady=10)
frame4.grid(row=3, column=0, padx=10, pady=10, sticky="nsew")

def multiply_matrices():
    global data_result, data, data2
    try:
        data_result = np.dot(data, data2)
        print(data_result)
        label_result.config(text=str(data_result))
    except Exception as e:
        messagebox.showerror("Error", f"{e}")

tk.Button(frame4, text="행렬 곱", fg="green", command=multiply_matrices).grid(row=0, column=0)

label_result = tk.Label(root, text=". . .", fg="black", font=("Arial", 16))
label_result.grid(row=4, column=0)

def plus_matrix():
    global data_result, data, data2
    try:
        data_result = data + data2
        label_result.config(text = str(data_result))
    except Exception as e:
        messagebox.showerror("Error", f"{e}")

tk.Button(frame4, text = "행렬 덧셈", fg = "purple", command = plus_matrix).grid(row = 0, column = 1)

# def dimention_setting():
#     global data, data2
#     list1 = list(range(1, 100))
#     list2 = list(range(1, 100))
#     row = 1
#     column = 1
#     try:
#         while data.shape[1] != data2.shape[1]:
#             row = random.choice(list1)
#             column = random.choice(list2)
#             data = data.reshape(row, column)
#             data2 = data2.reshape(row, column)
#         if data.shape[1] == data2.shape[1]:
#             label_first_matrix.config(text=str(data))
#             label_second_matrix.config(text=str(data2))
#     except Exception as e:
#         messagebox.showerror("뭔가 오류가 있군요...", f"{e}")




def dimention_setting():
    global data, data2
    try:
        min_columns = min(data.shape[1], data2.shape[1])
        data = data[:, :min_columns]
        data2 = data2[:, :min_columns]
        label_first_matrix.config(text=str(data))
        label_second_matrix.config(text=str(data2))
    except Exception as e:
        messagebox.showerror("뭔가 오류가 있군요...", f"{e}")

def broadcasting():
    global data, data2, data_result
    dimention_setting()
    try:
        data_result = data + data2
        label_result.config(text=str(data_result))
    except Exception as e:
        messagebox.showerror("Error", f"{e}")
    

tk.Button(frame4, text = "브로드캐스팅(??)", fg = "red", command = broadcasting).grid(row = 0, column = 2)

root.mainloop()

[  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.
  14.  15.  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.
  28.  29.  30.  31.  32.  33.  34.  35.  36.  37.  38.  39.  40.  41.
  42.  43.  44.  45.  46.  47.  48.  49.  50.  51.  52.  53.  54.  55.
  56.  57.  58.  59.  60.  61.  62.  63.  64.  65.  66.  67.  68.  69.
  70.  71.  72.  73.  74.  75.  76.  77.  78.  79.  80.  81.  82.  83.
  84.  85.  86.  87.  88.  89.  90.  91.  92.  93.  94.  95.  96.  97.
  98.  99. 100. 101. 102. 103. 104. 105. 106. 107. 108. 109. 110. 111.
 112. 113. 114. 115. 116. 117. 118. 119. 120. 121. 122. 123. 124. 125.
 126. 127. 128. 129. 130. 131. 132. 133. 134. 135. 136. 137. 138. 139.
 140. 141. 142. 143. 144. 145. 146. 147. 148. 149. 150. 151. 152. 153.
 154. 155. 156. 157. 158. 159. 160. 161. 162. 163. 164. 165. 166. 167.
 168. 169. 170. 171. 172. 173. 174. 175. 176. 177. 178. 179. 180. 181.
 182. 183. 184. 185. 186. 187. 188. 189. 190. 191. 192. 193. 194. 195.
 196. 